#!/bin/sh
# Parse arguments.
tag="$1"
spelled="$2"
if [ -z "$tag" ] || [ -z "$spelled" ]; then
  echo 'Example Usage: "1e" "First Edition"'
  exit 1
fi

# Check current branch.
branch=$(git branch --show-current)
if [ "$branch" != "main" ]; then
  echo 'Current branch is not "main"!'
  exit 1
fi

# Create tagged commit.
git checkout -b tmp
sed -i "s/^edition: Working Draft$/edition: $spelled/" ./*.md
git add ./*.md
git commit -m "$spelled"
git tag "$tag"
# Push.
git push origin "$tag"
# Build.
make
